[package]
name = "entities"
version = "0.1.0"
edition = "2021"

[dependencies]
accumulator = { version = "0.1.0", path = "../accumulator" }
blsful = "2.5.7"
merlin = "3.0.0"
rand_core = "0.6.4"
serde = "1.0.203"
